### PR TITLE
add Scenario 3: NYC Taxi dataset on Confidential AKS

### PR DESCRIPTION
**Pull request by clenimar**
Adds a new scenario on how to run a distributed Spark aggregation on a large dataset on Kubernetes. Just like the previous scenarios, driver and executors run on Scone (which leverages Intel SGX enclaves to provide integrity and confidentiality guarantees to the execution) and have their source codes encrypted.

TODO:

- [x] benchmark against vanilla Spark
- [x] performance tuning of the Scone runtime
- [x] make sure previous scenarios still work with the new base image (I changed the default entrypoint)...
- [ ] screencast

### CODE REVIEW

**Comment by mdrakiburrahman** [comment]
Thank you @clenimar, this is awesome - let me know as I can help on the TODOs.

I will be reproducing this in AKS (SGX VMs) as per the scenario documentation. I would also like to run this on a [Microk8s](https://microk8s.io/) cluster running on AMD CPUs, and non-SGX Intel CPUs.

If I understand correctly - the image `registry.scontain.com:5050/clenimar/pyspark:5.5.0-amd-experimental-k8s` should work on all three of these environments:
1. AKS (Intel SGX VMs) (as documented)
2. K8s cluster on AMD CPUs (experimental, and needs `SCONE_MODE=sim`)
3. K8s cluster on Intel non-SGX CPUs (since no SGX, needs `SCONE_MODE=sim`)

Is my understanding correct?

What I want to show here is that this `pyspark:5.5.0-amd-experimental-k8s` image will work in SIM mode on AMD + Intel CPUs without SGX for POCs, as well as with AKS SGX enabled chips - as designed for Production.

**Comment by clenimar** [comment]
Hey @mdrakiburrahman, yes, your understanding is correct about the three environments. I tested this scenario on both an ACC-enabled AKS cluster in HW mode and also on an AMD-based AKS cluster in SIM mode. Hopefully we'll be able to remove the _experimental_ label starting on the next release, we're just waiting for some AMD-related patches to land on master.

Please let me know if you have any issues reproducing the steps.

I'll be working on the benchmarks next, and writing some words on performance tuning of the SCONE runtime.

**Comment by clenimar** [comment]
Hey @mdrakiburrahman, I just pushed the results from a simple benchmark I ran today. The performance in the three scenarios was quite similar, which is pretty good. The scenarios considered were:

- Scone on Intel with SGX (HW mode)
- Scone on AMD (SIM mode)
- Vanilla on Intel (without SGX) - I ran this on the cluster with SGX, but obviously without using any of the SGX hardware. If you find this confusing to communicate to other people I can run it separately on a D2d_v4 cluster

Please let me know your thoughts on this. I think we should have a second workload with more complex stuff going on at some point, perhaps that would provide a better understanding of the trade-offs in the different scenarios.

Suggestions on how to improve the message here are more than welcome. The data I used to generate the graph is here:

```csv
label,executors,time,rep
scone_intel_hw,1,229.46301364898682,1
scone_intel_hw,1,285.7406532764435,2
scone_intel_hw,1,317.3509511947632,3
scone_intel_hw,2,121.6980311870575,1
scone_intel_hw,2,123.98698711395264,2
scone_intel_hw,2,118.67714953422546,3
scone_intel_hw,3,92.23479390144348,1
scone_intel_hw,3,86.45061373710632,2
scone_intel_hw,3,86.18780088424683,3
vanilla,1,223.41930770874023,1
vanilla,1,289.0072069168091,2
vanilla,1,258.76526951789856,3
vanilla,2,123.81887221336365,1
vanilla,2,154.28682827949524,2
vanilla,2,117.54598331451416,3
vanilla,3,81.68819761276245,1
vanilla,3,89.8803403377533,2
vanilla,3,77.23044943809509,3
scone_amd_sim,1,263.47832918167114,1
scone_amd_sim,1,306.5416188240051,2
scone_amd_sim,1,264.4081416130066,3
scone_amd_sim,2,139.16091060638428,1
scone_amd_sim,2,136.9455497264862,2
scone_amd_sim,2,139.34403705596924,3
scone_amd_sim,3,88.01262331008911,1
scone_amd_sim,3,83.01379561424255,2
scone_amd_sim,3,79.88614273071289,3
```

**Comment by mdrakiburrahman** [comment]
Hey @clenimar - I had a chance to go through the scenario end-to-end today - amazing job!

I realized you're a Mac User while going through the scenario. As a windows user running WSL, I ran into a couple of hiccups. Based on your latest commits from this PR, I made a couple enhancements to accommodate for WIndows users - you can view the commits [here](https://github.com/mdrakiburrahman/sgx-pyspark-sql-demo/commit/238951d6424a52326d5f48641ebb5d6888d638c9).

#### Changes made:
- **Dockerfile:**
    - Added in `dos2unix` for Windows > Bash cleanup
- Added in Scenario image
- Added in requests and limits to pod spec - was running into memory pressure without this
- **Readme:**
    - Small verbiage updates to existing verbiage
    - Added in a example pre-req setup steps for one-stop reference

I was having a tough time figuring out how to contribute those changes back to your fork so it rolls up into this PR, since it's a fork of my original repo. It might work if you gave me write access to your forked repo, but it's too much hassle.

So what I'm going to do is:
1. Merge this PR of yours now into `main`
2. Merge in my latest changes from the work done today, on top of this PR, into `main`

Going forward, I think we should work directly against this repository for further collaboration (screencasts etc), and avoid forks. I've given you collaborator access to the `mdrakiburrahman/sgx-pyspark-sql-demo` repo.

So from here, for future additions:
1. You can create a new branch `mdrakiburrahman/sgx-pyspark-sql-demo:nyctaxi-screencasts` etc.
2. I'm going to create a new branch called "Scenario 4", for running this scenario in SIM mode on a Microk8s amd cluster - just to showcase On-Prem usability in SIM mode
3. And we can directly open PR's against `mdrakiburrahman/sgx-pyspark-sql-demo:main`

Let me know if this doesn't make sense!

**Pull request merged**
